apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  labels:
    app: frontend
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25
  selector:
    matchLabels:   
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: public.ecr.aws/r2o2j9y1/three-tier-frontend:latest #  backend image from ECR
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://backend.amanpathakdevops.study/api/tasks"  


    