apiVersion: v1
kind: service
metadata:
  name: backend-service
  namespace: three-tier
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8181
    targetPort: 8181
  type: ClusterIP