apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tier
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
  template:
    metadata:
      labels: 
        app: mongodb

    spec:
      containers:
      - name: mangodb-container
        image: mongo:4.4.6
        command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
        ports:
        - containerPort: 27017 
        env:
          - name: MONGO-DB-ROOT-USERNAME
            valueFrom: 
              secretKeyRef:
                name: mongodb
                key: username
          
          - name: MONGO-DB-ROOT-PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb
                key: password
    